apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devspace-default-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devspace-default-clusterrole
subjects:
- kind: ServiceAccount
  name: devspace-default
  namespace: {{ .Release.Namespace }}