apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: devspace-default-podsecuritypolicy
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - configMap
    - emptyDir
    - downwardAPI
    - persistentVolumeClaim
