apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devspace-manager-clusterrole
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - extensions
      - policy
    resourceNames:
      - devspace-manager-podsecuritypolicy
    resources:
      - podsecuritypolicies
    verbs:
      - use
