{{- $certManager := index .Values "cert-manager" -}}
{{- if $certManager.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: devspace-self-signed
spec:
  selfSigned: {}
{{- end -}}