{{- if .Values.ingress.tls.enabled -}}
{{- $certManager := index .Values "cert-manager" -}}
{{- if $certManager.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: devspace-cert
spec:
  secretName: tls-devspace-cloud
  dnsNames:
  {{- range $index, $domain := .Values.ingress.domains }}
    - "{{ $domain }}"
  {{- end }}
  issuerRef:
    name: lets-encrypt-http-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
{{- end -}}
{{- end -}}