{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devspace-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    {{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  rules:
  {{- range $index, $domain := .Values.ingress.domains }}
  - host: "{{ $domain }}"
    http:
      paths:
      - path: /auth
        backend:
          serviceName: devspace-auth
          servicePort: 8080
      - path: /
        backend:
          serviceName: devspace-ui
          servicePort: 8080
      - path: /v1
        backend:
          serviceName: devspace-hasura
          servicePort: 8080
      - path: /console
        backend:
          serviceName: devspace-hasura
          servicePort: 8080
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range $index, $domain := .Values.ingress.domains }}
    - "{{ $domain }}"
    {{- end }}
    secretName: tls-devspace-cloud
  {{- end -}}
{{- end -}}