apiVersion: v1
kind: Service
metadata:
  name: devspace-postgres-headless
  labels:
    app: devspace-postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: devspace-postgres
